import LegalPage, { Contents, Section, SubSection, Callout, Table, Colophon } from "@/components/legal/LegalPage";

const EFFECTIVE_DATE = "06/30/2026";
const LAST_UPDATED = "10/02/2026";
const CONTACT_EMAIL = "animesh@sourcemaverick.ai";

const contents = [
  { id: "s1", label: "Introduction" },
  { id: "s2", label: "Who We Are" },
  { id: "s3", label: "Information We Collect" },
  { id: "s4", label: "How We Use Your Information" },
  { id: "s5", label: "Third-Party Service Providers" },
  { id: "s6", label: "Data We Do Not Sell" },
  { id: "s7", label: "Data Retention" },
  { id: "s8", label: "Data Security" },
  { id: "s9", label: "Your Rights" },
  { id: "s10", label: "AI Transparency" },
  { id: "s11", label: "Spiritual Personas" },
  { id: "s12", label: "Wellness Platform" },
  { id: "s13", label: "Children's Privacy" },
  { id: "s14", label: "California Rights" },
  { id: "s15", label: "GDPR (EU Users)" },
  { id: "s16", label: "India (DPDP)" },
  { id: "s17", label: "Changes" },
  { id: "s18", label: "Contact Us" },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      label="Legal"
      title="Privacy Policy"
      meta={
        <>
          <p>Effective Date: {EFFECTIVE_DATE} · Last Updated: {LAST_UPDATED}</p>
        </>
      }
    >
        <Contents items={contents} />

        <Section id="s1" title="1. Introduction — What This Policy Covers">
          <p>
            Source is a conversational AI platform built by Super Real Inc. that brings ancient spiritual teachings to life through AI-powered personas. This Privacy Policy explains what personal information we collect when you use the Source app, why we collect it, how we use and protect it, and what rights and choices you have.
          </p>
          <p className="mt-3">
            We have written this section in plain language first. The detailed legal obligations specific to your region (California, the European Union, and India) appear in Sections 14 through 16.
          </p>
          <Callout title="In brief">
            We collect information you give us directly (your email, the name you want to be called, optionally your pronouns and the reason you came), information generated by your use of the app (your messages, transcripts of your voice messages, the persona's replies, and the memories and summaries derived from them), and technical data from your device. To work, Source sends what you say to AI services run by other companies, named in Section 5; the app asks for your permission before anything is sent. We do not sell your personal data. We do not hand your conversations to any company to train its AI models. You can read what the persona remembers, remove any memory, or delete your account and your data at any time from within the app.
          </Callout>
        </Section>

        <Section id="s2" title="2. Who We Are and How to Contact Us">
          <p>Source is operated by Super Real Inc., a Delaware C-Corporation ("Super Real," "we," "us," or "our").</p>
          <Table headers={["Contact Type", "Details"]} rows={[
            ["Legal Entity", "Super Real Inc."],
            ["Registered State", "Delaware, United States"],
            ["Privacy Contact Email", "animesh@sourcemaverick.ai"],
            ["Mailing Address", "16192 Coastal Hwy. Lewes, DE 19958, USA"],
            ["GDPR Data Controller", "Super Real Inc. (see Section 15)"],
            ["DPDP Grievance Officer", "Animesh Anand, animesh@sourcemaverick.ai (see Section 16)"]
          ]} />
          <p className="mt-4">We aim to respond to all privacy-related enquiries within 30 days of receipt.</p>
        </Section>

        <Section id="s3" title="3. Information We Collect">
          <p>We collect the following categories of personal information:</p>

          <SubSection title="3.1 Account and Identity Information">
            <ul className="space-y-2">
              <li>Email address – required to create and maintain your account</li>
              <li>The name you want to be called – provided at registration or onboarding</li>
              <li>Pronouns and the reason you came – optional, typed during onboarding</li>
              <li>Profile picture – optionally provided by you</li>
              <li>Sign-in identifier from Apple, Google or Firebase – used for authentication and session management</li>
            </ul>
          </SubSection>

          <SubSection title="3.2 Conversation Data">
            <ul className="space-y-2">
              <li>The full text of your messages, transcripts of the voice messages you record, and the AI persona's responses across all sessions</li>
              <li>Derived memory data – short memories, a summary and a reflection written at the end of each session, and patterns noticed across sessions, built from your own words and used to personalise your future sessions; these are shown to you in the app</li>
              <li>Meditation history and journal entries you create</li>
            </ul>
            <p className="mt-2 text-sm text-white/40">Conversation transcripts and derived memory data are retained for the lifetime of your account. For details on how and why, see Section 7 (Data Retention).</p>
          </SubSection>

          <SubSection title="3.3 Usage and Behavioural Data">
            <ul className="space-y-2">
              <li>Session length, return frequency, and content engagement signals</li>
              <li>Features accessed, screens visited, and session timestamps</li>
              <li>All behavioural data is linked to your account identity</li>
            </ul>
          </SubSection>

          <SubSection title="3.4 Technical and Device Data">
            <ul className="space-y-2">
              <li>IP address, kept in server logs for security and abuse prevention</li>
              <li>Device model, operating system version, app version, and your time zone</li>
              <li>App analytics, collected via Firebase Analytics only if you allow tracking when iOS asks</li>
              <li>Push notification token, if you allow notifications, so we can send the daily message</li>
            </ul>
          </SubSection>

          <SubSection title="3.5 User Feedback">
            <ul className="space-y-2">
              <li>Ratings, reactions, and written comments you provide on AI responses</li>
            </ul>
          </SubSection>

          <SubSection title="3.6 Voice and Audio Input">
            <p>If you record a voice message in the In-depth Conversation room, the recording is sent to our servers and transcribed by Groq (a speech-to-text service). The audio is deleted as soon as the transcript exists; only the transcript is kept. In the Casual Conversation (call) room, your voice is streamed live to ElevenLabs, which transcribes it and runs the conversation in real time; we do not record your voice. The persona's spoken replies are stored on Google Cloud so you can replay them.</p>
          </SubSection>

          <Callout title="What we do NOT collect">
            Source does not collect precise GPS location, camera data, biometric identifiers, health information, or data from other apps. Payment card data is never collected or stored by Source – subscription billing is handled entirely by Apple or Google (see Section 3.7).
          </Callout>

          <SubSection title="3.7 Subscription and Payment Data">
            <p>Source sells coins through Apple In-App Purchase and Google Play Billing. Payment is handled entirely by Apple or Google; Source never collects, stores, or has access to your payment card details. RevenueCat records which coin packs you bought and when, so your coins arrive and can be restored.</p>
          </SubSection>
        </Section>

        <Section id="s4" title="4. How We Use Your Information">
          <p>We use personal information only for the following purposes:</p>
          <Table headers={["Purpose", "Data Used", "Legal Basis (GDPR)"]} rows={[
            ["Providing the Source service – generating the persona's replies and voice, memory personalisation, and account management", "Account data, conversation data, derived memory data", "Performance of contract, and your permission (given in the app before anything is sent to an AI service)"],
            ["Safety – every message is checked for signs of crisis so the persona can respond with care and local helpline numbers", "Conversation data", "Legitimate interests / vital interests"],
            ["Service improvement and quality – analysing usage patterns and feedback to improve the platform", "Usage data, feedback, anonymised conversation analytics", "Legitimate interests"],
            ["Technical operations – crash reporting, debugging, and infrastructure stability", "Crash and diagnostic data, device data", "Legitimate interests"],
            ["Communications – transactional emails such as account confirmation, policy updates, and service notices", "Email address", "Performance of contract / Legal obligation"],
            ["Legal compliance and safety – responding to lawful legal process; detecting and preventing fraud or abuse", "Account data, usage data", "Legal obligation"]
          ]} />
          <p className="mt-4">We do not use your personal data for automated decision-making that produces legal or similarly significant effects on you.</p>
        </Section>

        <Section id="s5" title="5. Third-Party Service Providers">
          <p>We share personal data only with the following service providers who are contractually obligated to process it only on our behalf and in accordance with this policy:</p>
          <Table headers={["Provider", "Role", "Data Shared", "Model Training?"]} rows={[
            ["Anthropic (Claude API)", "Writes the persona's replies, the session summaries and the memories, and runs the safety check", "Your messages, your name and pronouns, what the persona remembers about you, and the recent conversation", "No – Anthropic does not train its models on data sent through its API"],
            ["ElevenLabs", "Turns the persona's replies into his voice; in the call room, transcribes your voice and runs the conversation live", "The reply text, and in calls, your voice", "No"],
            ["Groq", "Transcribes the voice messages you record; stands in as the reply writer only if Anthropic is unavailable", "Your voice recordings, and during an outage, the same data as Anthropic", "No"],
            ["Google Cloud", "Hosts our servers and database; stores the persona's spoken replies", "Everything listed in Section 3, stored in the United States", "No – infrastructure only"],
            ["Google Firebase", "Sign in, push notifications, and usage analytics if you allowed tracking", "Sign-in identifier, notification token, app usage data, device metadata", "N/A – governed by Google's privacy terms"],
            ["Qdrant", "Keeps a searchable index of your memories so the persona can find the relevant ones", "The text of your memories and your account identifier", "No"],
            ["RevenueCat", "Records purchases so your coins arrive and can be restored", "Your account identifier and purchase receipts", "N/A"],
            ["Apple / Google", "Payment processing and sign in", "A purchase receipt – no payment card data", "N/A"]
          ]} />
          <p className="mt-4">Each provider receives only what it needs for its job and is bound by its own privacy terms, which provide the same or equal protection as this policy. We do not share personal data with advertisers, data brokers, or any third party for marketing purposes. We do not sell personal data. If we add a provider that receives your personal data, we will update this policy and ask for your permission again in the app.</p>
          <Callout title="Your permission">
            Before your first conversation, the app shows you what is sent (your messages and voice, your name, pronouns and reason for coming, and what the persona remembers) and to whom (the providers above), and asks for your permission. Nothing is sent until you agree. If you do not agree, you can still use the meditation practices, but not the conversations. Deleting your account withdraws the permission.
          </Callout>
          <Callout title="Note on Firebase">
            Firebase Analytics links usage data to device identifiers. This constitutes a transfer of personal data to Google. Google's data processing terms govern Firebase's use of this data. By using Source, you acknowledge that app analytics data is processed by Google under Firebase's standard terms.
          </Callout>
        </Section>

        <Section id="s6" title="6. Data We Do Not Sell or Use for Advertising">
          <p>Source does not:</p>
          <ul className="space-y-2">
            <li>Sell your personal data to any third party</li>
            <li>Share your conversational data with advertisers or marketing platforms</li>
            <li>Use your personal data for behavioural advertising, targeted advertising, or profiling for commercial purposes</li>
            <li>Allow third parties to collect your data through Source for their own advertising purposes</li>
          </ul>
          <p className="mt-4">This applies equally to California residents' rights under CCPA/CPRA. See Section 14 for your specific California rights.</p>
        </Section>

        <Section id="s7" title="7. Data Retention">
          <Table headers={["Data Type", "Retention Period", "Upon Account Deletion"]} rows={[
            ["Profile data (name, pronouns, reason for coming, photo, email)", "Duration of active account", "Deleted immediately"],
            ["Derived memory, summaries and reflections", "Duration of active account", "Deleted immediately, including the memory index at Qdrant"],
            ["Meditation history and journal entries", "Duration of active account", "Deleted immediately"],
            ["The persona's spoken replies (audio)", "Duration of active account", "Deleted immediately"],
            ["Your voice recordings", "Not retained – deleted as soon as they are transcribed", "N/A"],
            ["Conversation text", "Duration of active account", "Kept with your name, email and identifiers removed, so it can no longer be connected to you; used only to improve the persona's teaching material"],
            ["Purchase records", "Duration of active account", "Kept where tax law requires"],
            ["Analytics data (Firebase)", "Per Google/Firebase retention settings", "Per Google/Firebase retention settings"]
          ]} />
          <p className="mt-4">When you delete your account, deletion in our own systems happens at once, in a single operation, and we ask each provider in Section 5 to delete what it holds. No personal data is retained following account deletion unless a binding legal obligation requires it.</p>
          <Callout title="Note on retention">
            Conversation text and memories are retained for the full duration of your account so the persona can remember you. You can read every memory and remove any of them from within the app (Journey, then Memory) without deleting your account. Deleting your account removes everything that identifies you; the de-identified conversation text described above is all that remains.
          </Callout>
        </Section>

        <Section id="s8" title="8. Data Security">
          <p>We implement the following technical and organisational measures to protect your personal data:</p>
          <ul className="space-y-2">
            <li>Encryption in transit: All data transmitted between the Source app and our servers uses TLS/HTTPS encryption</li>
            <li>Encryption at rest: User data stored on Source servers is encrypted using AES-256</li>
            <li>Access controls: Conversation data is accessible internally only to personnel who require it for technical operations</li>
            <li>Incident response: We maintain a data breach response plan with defined procedures for containment, notification, and remediation</li>
          </ul>
          <p className="mt-4">No method of electronic transmission or storage is completely secure. While we take these measures seriously, we cannot guarantee absolute security. In the event of a data breach that is likely to result in a risk to your rights and freedoms, we will notify you and relevant authorities in accordance with applicable law.</p>
        </Section>

        <Section id="s9" title="9. Your Rights and Choices">
          <p>You have the following rights regarding your personal data:</p>
          <Table headers={["Right", "What It Means", "How to Exercise"]} rows={[
            ["Access", "Request a copy of the personal data we hold about you", "Contact animesh@sourcemaverick.ai"],
            ["Correction", "Ask us to correct inaccurate or incomplete data", "In-app profile settings or via email"],
            ["Deletion", "Request deletion of your account and all associated personal data", "In-app account deletion or via email"],
            ["Portability", "Receive a copy of your personal data in a machine-readable format", "Contact animesh@sourcemaverick.ai"],
            ["Memory", "Read what the persona remembers and remove any memory without deleting your account", "Journey, then Memory, in the app"],
            ["Withdraw AI permission", "Stop your words being sent to the AI services in Section 5", "Delete your account in the app; the conversations cannot run without them"],
            ["Analytics", "Allow or refuse usage analytics", "iOS: Settings, Privacy, Tracking. Android: in-app settings"]
          ]} />
          <p className="mt-4">We will respond to all rights requests within 30 days. If you are an EU user or an Indian user, additional rights apply – see Sections 15 and 16 respectively.</p>
        </Section>

        <Section id="s10" title="10. AI Transparency and Disclosure">
          <p>Source is an artificial intelligence platform. The following disclosures are made in compliance with applicable law and in the interest of your informed use of the service.</p>

          <SubSection title="10.1 You Are Interacting with AI, Not a Human">
            <p>All conversations on Source are with AI constructs. You are not speaking with a human being, a living spiritual teacher, or the actual consciousness or spirit of any historical individual. Source's personas are AI systems trained on the publicly available teachings, writings, and documented philosophy of historical spiritual figures. They are not channels to, representations of, or communications from, any living or deceased person.</p>
            <p className="mt-2">In compliance with New York law (effective November 2025), Source will periodically remind users during interactions that they are engaging with an AI system.</p>
            <p className="mt-2">In compliance with California AB 3030 (effective January 2025), Source discloses that communications generated within the app are produced by artificial intelligence.</p>
          </SubSection>

          <SubSection title="10.2 AI Responses Are Not Infallible">
            <p>AI-generated responses may not always be accurate, complete, or appropriate for your specific circumstances. Source's personas offer spiritual and contemplative guidance rooted in their respective traditions; they do not provide personalised professional advice. For matters of health, law, finance, or personal safety, please consult a qualified professional.</p>
          </SubSection>

          <SubSection title="10.3 Source's Memory System">
            <p>Source uses a proprietary persistent memory architecture that retains contextual information from your previous conversations. This allows Source to personalise your experience over time – recalling earlier context much as an experienced teacher would. When you return to Source, the AI you interact with will have memory of your prior sessions.</p>
            <p className="mt-2">Memories are stored in our database and indexed at Qdrant so the relevant ones can be found during a conversation. You can read and remove them at any time from within the app without deleting your account. Memory data, including the index, is deleted immediately when you delete your account.</p>
          </SubSection>
        </Section>

        <Section id="s11" title="11. Spiritual Master Personas — Identity and Authorisation">
          <p>Source creates AI personas inspired by and built upon the teachings of historical spiritual figures. The following principles govern how we create and present these personas.</p>

          <SubSection title="11.1 Partnership-Based Creation">
            <p>Source works in formal partnership with organisations connected to the lineages and estates of the spiritual masters whose teachings inform our personas. We obtain documented authorisation covering the use of each master's name, publicly available teachings, and identity as the basis for an AI construct, prior to making any such persona available in the app.</p>
          </SubSection>

          <SubSection title="11.2 What Our Personas Are and Are Not">
            <ul className="space-y-2">
              <li>Source personas ARE AI systems inspired by the documented teachings and philosophy of historical spiritual figures</li>
              <li>Source personas are NOT channels to, direct representations of, or communications from, any living or deceased individual</li>
              <li>Source does NOT claim that any persona constitutes contact with, or communication from, any spiritual master, living or deceased</li>
              <li>Source personas are educational and contemplative tools, not representations of any actual person</li>
            </ul>
          </SubSection>

          <SubSection title="11.3 Right of Publicity Compliance">
            <p>Source's authorisation process is designed to comply with applicable right of publicity laws, including New York's posthumous right of publicity law (enacted December 2025) and California AB 1836. We obtain written authorisation from relevant lineage organisations or estates prior to launch of each persona. If you believe a persona infringes applicable right of publicity law, please contact us at animesh@sourcemaverick.ai.</p>
          </SubSection>
        </Section>

        <Section id="s12" title="12. Source Is a Wellness Platform – Not a Therapeutic Service">
          <p>This is one of the most important disclosures in this policy. Please read it carefully.</p>

          <SubSection title="12.1 What Source Is">
            <ul className="space-y-2">
              <li>A wellness and personal development platform</li>
              <li>A tool for spiritual guidance, contemplative reflection, and self-exploration rooted in ancient traditions</li>
              <li>A supplement to – not a replacement for – professional mental health care, medical treatment, or crisis intervention</li>
            </ul>
          </SubSection>

          <SubSection title="12.2 What Source Is Not">
            <ul className="space-y-2">
              <li>Source is NOT a licensed mental health service, therapy, counselling, or psychiatric platform</li>
              <li>Source is NOT a medical device and does not diagnose, treat, cure, or prevent any medical or psychological condition</li>
              <li>Source is NOT a crisis intervention or emergency service</li>
              <li>Source is NOT a substitute for professional psychological, psychiatric, or medical care</li>
              <li>Source is NOT covered by HIPAA. Source is not a healthcare provider. Conversations with Source do not carry HIPAA protection</li>
              <li>Source conversations are NOT legally privileged. Unlike sessions with a licensed therapist, your conversations with Source could be subject to lawful legal process</li>
            </ul>
          </SubSection>

          <Callout title="California AB 489 Compliance (effective 2025)">
            California law prohibits AI systems from presenting themselves as licensed healthcare providers. No Source persona uses titles such as therapist, psychologist, counselor, psychiatrist, or doctor, or implies that it is a licensed practitioner of any kind.
          </Callout>

          <SubSection title="12.3 If You Are in Crisis">
            <p>Source does not monitor conversations in real time and cannot provide emergency intervention. If you are experiencing a mental health crisis, thoughts of self-harm, or any emergency, please contact:</p>
            <ul className="space-y-1 text-sm">
              <li>Emergency services: 911 (USA), 112 (EU), 112 (India)</li>
              <li>988 Suicide and Crisis Lifeline (USA): Call or text 988</li>
              <li>Crisis Text Line (USA): Text HOME to 741741</li>
              <li>iCall (India): +91-9152987821</li>
              <li>Samaritans (UK): 116 123</li>
            </ul>
          </SubSection>
        </Section>

        <Section id="s13" title="13. Children's Privacy">
          <p>Source is for adults. You must be 18 or older to use it. We do not knowingly collect personal data from anyone under 18.</p>
          <ul className="space-y-2">
            <li>Users confirm that they are at least 18 years old before they begin</li>
            <li>If we become aware that a user is under 18, their account and all associated data will be deleted promptly</li>
            <li>If you believe someone under 18 has created a Source account, please contact us at animesh@sourcemaverick.ai</li>
          </ul>
          <p className="mt-4">For users in the European Union: GDPR Article 8 requires parental consent for users below the applicable age of digital consent in their country (which varies between 13 and 16 depending on the EU member state). EU users between 13 and 16 may be required to obtain parental consent before using Source. We will implement age verification or parental consent mechanisms in our EU rollout in compliance with these requirements.</p>
          <p className="mt-4">Source's content addresses mature philosophical and existential themes. The platform is not designed for, marketed to, or appropriate for minors.</p>
        </Section>

        <Section id="s14" title="14. California Privacy Rights (CCPA / CPRA)">
          <p>This section applies to residents of California and supplements the rights described in Section 9.</p>

          <SubSection title="14.1 Categories of Personal Information We Collect">
            <p>Under CCPA/CPRA, the categories of personal information we collect include: identifiers (name, email, device ID, IP address); internet or other network activity (usage data, session data, crash logs); audio information (voice input, processed on-device only, not retained); inferences drawn from personal information (derived memory and contextual profiles); and commercial information (subscription status).</p>
          </SubSection>

          <SubSection title="14.2 Do Not Sell or Share My Personal Information">
            <p>Source does not sell your personal information. Source does not share your personal information with third parties for cross-context behavioural advertising. You therefore have no opt-out to exercise for sale or sharing – we do not engage in these practices. We will update this section if our practices change.</p>
          </SubSection>

          <SubSection title="14.3 Your CCPA / CPRA Rights">
            <ul className="space-y-2">
              <li>Right to Know: Request disclosure of the categories and specific pieces of personal information we have collected about you</li>
              <li>Right to Delete: Request deletion of your personal information, subject to limited legal exceptions</li>
              <li>Right to Correct: Request correction of inaccurate personal information</li>
              <li>Right to Opt-Out of Sale/Sharing: Not applicable – we do not sell or share personal information</li>
              <li>Right of Non-Discrimination: We will not discriminate against you for exercising any of your CCPA rights</li>
            </ul>
            <p className="mt-2">To exercise your California rights, contact us at animesh@sourcemaverick.ai or use the in-app account management tools. We will respond within 45 days (extendable by an additional 45 days with notice where reasonably necessary).</p>
          </SubSection>
        </Section>

        <Section id="s15" title="15. European Union Users (GDPR)">
          <p>This section applies to users in the European Economic Area (EEA), the United Kingdom, and Switzerland, and supplements Section 9.</p>

          <SubSection title="15.1 Data Controller">
            <p>Super Real Inc. is the data controller for personal data processed through Source. Our contact details are in Section 2.</p>
          </SubSection>

          <SubSection title="15.2 Legal Bases for Processing">
            <Table headers={["Processing Activity", "Legal Basis"]} rows={[
              ["Providing the Source service (conversations, account management, memory)", "Performance of contract (Art. 6(1)(b))"],
              ["Service improvement and analytics", "Legitimate interests (Art. 6(1)(f)) – to improve the quality of our platform"],
              ["Transactional communications", "Performance of contract (Art. 6(1)(b))"],
              ["Legal compliance", "Legal obligation (Art. 6(1)(c))"],
              ["Sending your words to the AI service providers in Section 5", "Consent (Art. 6(1)(a)), given in the app before anything is sent, and performance of contract (Art. 6(1)(b))"],
              ["Safety check of messages", "Legitimate interests (Art. 6(1)(f)) and vital interests (Art. 6(1)(d))"]
            ]} />
          </SubSection>

          <SubSection title="15.3 International Data Transfers">
            <p>Source is operated from the United States. If you are located in the EEA, your personal data will be transferred to and processed in the United States. We implement appropriate safeguards for such transfers, including Standard Contractual Clauses (SCCs) as approved by the European Commission, where applicable. For transfers to Anthropic and Google Firebase, we rely on the data processing agreements and transfer mechanisms established by those providers.</p>
          </SubSection>

          <SubSection title="15.4 Your GDPR Rights">
            <p>In addition to the rights in Section 9, EU users have the right to:</p>
            <ul className="space-y-2">
              <li>Object to processing based on legitimate interests</li>
              <li>Restriction of processing in certain circumstances</li>
              <li>Lodge a complaint with your national data protection authority (DPA)</li>
            </ul>
          </SubSection>

          <SubSection title="15.5 Data Breach Notification">
            <p>In the event of a personal data breach that is likely to result in a risk to your rights and freedoms, we will notify the relevant supervisory authority within 72 hours of becoming aware, and will notify affected users without undue delay where required.</p>
          </SubSection>

          <SubSection title="15.6 Data Protection Officer">
            <p>Given our current scale, we have assessed that a formal DPO appointment is not yet required under GDPR. We will appoint a DPO when our processing activities require it. Privacy enquiries can be directed to animesh@sourcemaverick.ai</p>
          </SubSection>
        </Section>

        <Section id="s16" title="16. Indian Users (Digital Personal Data Protection Act, 2023)">
          <p>This section applies to users in India and supplements Section 9.</p>

          <SubSection title="16.1 Consent-Based Processing">
            <p>Under India's Digital Personal Data Protection Act (DPDP Act), 2023, we process your personal data on the basis of your free, specific, informed, unconditional, and unambiguous consent, given at the time of registration. You may withdraw consent at any time by deleting your account. Withdrawal of consent will not affect the lawfulness of processing carried out prior to withdrawal.</p>
          </SubSection>

          <SubSection title="16.2 Grievance Officer">
            <p>In compliance with the DPDP Act, we have designated a Grievance Officer for Indian users:</p>
            <ul className="space-y-2">
              <li>Name: Animesh Anand</li>
              <li>Email: animesh@sourcemaverick.ai</li>
              <li>Response time: We will acknowledge grievances within 48 hours and resolve them within 30 days</li>
            </ul>
          </SubSection>

          <SubSection title="16.3 Your Rights Under the DPDP Act">
            <ul className="space-y-2">
              <li>Right to access information about your personal data we hold</li>
              <li>Right to correction and erasure of inaccurate or incomplete data</li>
              <li>Right to grievance redressal through our Grievance Officer</li>
              <li>Right to nominate another person to exercise your rights in the event of your death or incapacity</li>
            </ul>
          </SubSection>

          <SubSection title="16.4 Data Localisation">
            <p>We are monitoring guidance from the Indian government regarding data localisation requirements under the DPDP Act. We will update this section and our data handling practices as regulatory requirements are clarified and come into force.</p>
          </SubSection>

          <SubSection title="16.5 Cross-Border Data Transfers">
            <p>Your personal data may be transferred to and processed in the United States, where our servers and service providers (including Anthropic, ElevenLabs, Groq, Google Cloud and Firebase, Qdrant and RevenueCat) are located. We will comply with applicable requirements under the DPDP Act regarding cross-border data transfers, including any restrictions notified by the Central Government.</p>
          </SubSection>
        </Section>

        <Section id="s17" title="17. Changes to This Policy">
          <p>We may update this Privacy Policy from time to time. When we make material changes, we will:</p>
          <ul className="space-y-2">
            <li>Notify you through an in-app notification at least 30 days before the change takes effect</li>
            <li>Send a notification to the email address associated with your account</li>
            <li>Update the Last Updated date at the top of this document</li>
            <li>If the change affects what is sent to AI services or to whom, ask for your permission again in the app before you continue</li>
          </ul>
          <p className="mt-4">Your continued use of Source after the effective date of an updated policy constitutes your acceptance of the changes. If you do not agree with a material change, you may delete your account before the effective date.</p>
        </Section>

        <Section id="s18" title="18. Contact Us">
          <p>For any questions, concerns, or requests relating to this Privacy Policy or your personal data, please contact us:</p>
          <Table headers={["Method", "Details"]} rows={[
            ["Privacy email", CONTACT_EMAIL],
            ["Mailing address", "Super Real Inc., 16192 Coastal Hwy. Lewes, DE 19958, USA"],
            ["In-app", "Settings – Privacy – Contact Us"],
            ["Response commitment", "We aim to respond within 30 days of receiving your request"]
          ]} />
          <p className="mt-4">If you are not satisfied with our response, you have the right to escalate your complaint to the relevant data protection authority in your jurisdiction (see Sections 14–16 for jurisdiction-specific details).</p>
        </Section>

        <Colophon>
          <p>Super Real Inc. · Source App · Privacy Policy · Version 1.1<br/>
            © {new Date().getFullYear()} Super Real Inc. All rights reserved.</p>
        </Colophon>
    </LegalPage>
  );
}
